### PR TITLE
fix(button): set focus outline to transparent

### PR DESCRIPTION
**Pull request by rachelbt**

### CODE REVIEW

**Review by yinonov — COMMENTED** [review]
I recall it was mentioned in the article u shared. can u please describe how this helps?
consider we do have a dedicated element to reflect outline and we don't want this style to be visible on certain preferences

**Comment by rachelbt** [comment]
> I recall it was mentioned in the article u shared. can u please describe how this helps? consider we do have a dedicated element to reflect outline and we don't want this style to be visible on certain preferences

all is in the issue:
https://github.com/Vonage/vivid-3/issues/415

**Comment by YonatanKra** [comment]
What about other `outline: none` and `outline: 0 none` in our code?
Namely sidenav item, text-field etc.

**Comment by rachelbt** [comment]
> What about other `outline: none` and `outline: 0 none` in our code? Namely sidenav item, text-field etc.

didn't want to do them both in the same issue, cause they are not the same.
Buttons actually has focus component inside them - so it may be that we can set focus none on buttons.

**Review by YonatanKra — APPROVED** [review]

**Comment by rachelbt** [comment]
due to the face that we are setting a color of the outline  in the focus component that is inside button - I'm closing this isusse.

**Pull request closed without merging**
