### PR TITLE
feat(docs): add toc (VIV-1728)

### PR DESCRIPTION
**Pull request by RichardHelm**

### CODE REVIEW

**Review by rachelbt — COMMENTED** [review]
This is soooo helpful!
Its the first component in our docs that we are not using one o vivid's components :( But I guess its not worth creating it from scratch when we can use the plugin.

I personally like the design but it looks a bit not "vivid". WDYT about this:
image
.article-toc a[aria-active]::before {
    content: "";
    display: block;
    block-size 100%;
    background-color: currentColor;
    inline-size: 2px;
    position: absolute;
    inset-inline-start: -9px;
    z-index: 1;
    inset-block-start: 0;
}
and this to the a:
    border-radius: 8px;
    border: 0;
    margin-inline-start: 8px;
    position: relative;

**Comment by RichardHelm** [comment]
@rachelbt Sure, I updated the design now

**Review by rachelbt — COMMENTED** [review]
👍 
BTW, is there an option to add classes instead of targeting html elements?

**Comment by RichardHelm** [comment]
@rachelbt No, doesn't seem like it

**Review by rachelbt — APPROVED** [review]

**Pull request merged**
