### PR TITLE
docs(design-tokens): add new readme

### PR DESCRIPTION
**Pull request by AyalaBu**

### CODE REVIEW

**Review by AyalaBu — COMMENTED** [review]
Edited a table in the readme file

**Review by AyalaBu — COMMENTED** [review]
Table view was updated

**Review by AyalaBu — COMMENTED** [review]
Added an img to a file

**Review by AyalaBu — COMMENTED** [review]
Added images to a readme

**Review by rinaok — APPROVED** [review]

**Comment by AyalaBu** [comment]
Merged the branched,
Need to have another look at the table

**Pull request merged**
