### PR TITLE
fix(banner): fix control being focusable (VIV-1414)

### PR DESCRIPTION
**Pull request by RichardHelm**

### CODE REVIEW

**Comment by rachelbt** [comment]
vivid-2 banner (material) is tubbable. 
Do we really don't need the banner to be in the tab keyboard navigation?

**Review by TaylorJ76 — APPROVED** [review]

**Comment by RichardHelm** [comment]
@rachelbt Why should a banner be focusable? It's non-interactive

**Comment by rachelbt** [comment]
> @rachelbt Why should a banner be focusable? It's non-interactive

not sure.
pointed out the fact that it was in vivid-2. Not that vivid-2 was accessible but wondered if it was there for a reason

**Comment by RichardHelm** [comment]
It was probably is mistake in Vivid 2 as well. I checked some other sites and their banners are non-focusable as expected

**Pull request merged**
