### PR TITLE
feat(form-elements): icon change

### PR DESCRIPTION
**Pull request by rachelbt**

### CODE REVIEW

**Review by olaf-k — COMMENTED** [review]
should this have its own ui test?

**Comment by rachelbt** [comment]
> should this have its own ui test?

not sure we need...
@YonatanKra WDTS?

**Comment by yinonov** [comment]
> > should this have its own ui test?
> 
> not sure we need... @YonatanKra WDTS?

@YonatanKra this raises the question of how success can be authored while error should be triggered

**Comment by YonatanKra** [comment]
@yinonov - I think handling the `success` message is not part of the scope of this PR. This PR only changes the icons.

**Review by olaf-k — APPROVED** [review]
LGTM

**Pull request merged**
