### PR TITLE
fix(fonts): force usage of proprietary fonts (VIV-1090)

### PR DESCRIPTION
**Pull request by gullerya**
Right now the value of `font-display` is `optional`, which means that browser gives up very quickly on the usage of the correct font and stays with the fallback. This causes in most cases the effect that first render of the page stays on a fallback fonts and only refresh brings the brand fonts, which is unacceptable in the branded application cases. `block` suggested here (or you may consider `swap` as well) will make the swap period infinite and eventually will render the branded fonts, which is the desired behavior in the proprietary Vonage applications page.

### CODE REVIEW

**Review by olaf-k — APPROVED** [review]
looks good. @rachelbt any counter indication?

**Comment by YonatanKra** [comment]
@rachelbt - any objections?

**Comment by rachelbt** [comment]
> @rachelbt - any objections?

no. we can merge

**Comment by gullerya** [comment]
Cool, when do you think we can get a release version that will include this?

**Pull request merged**
