### PR TITLE
chore(components): hover and active states precede selected

### PR DESCRIPTION
**Pull request by yinonov**

### CODE REVIEW

**Review by rachelbt — COMMENTED** [review]
Makes sense.
But what about checked? shouldn't it get it as well?
Were did you accoutred the issue - I see that in menu item the selected doesn't have hover running over its colors.

**Comment by yinonov** [comment]
> Makes sense.
> 
> But what about checked? shouldn't it get it as well?
> 
> Were did you accoutred the issue - I see that in menu item the selected doesn't have hover running over its colors.

Can u elaborate please?

**Comment by rachelbt** [comment]
> > Makes sense.
> > But what about checked? shouldn't it get it as well?
> > Were did you accoutred the issue - I see that in menu item the selected doesn't have hover running over its colors.
> 
> Can u elaborate please?

if selected has override upon hover + active, shouldn't checked be too? 
In menu item has selected class it hoesn't have hover state:
https://vivid.deno.dev/components/nav-item
image

**Review by rachelbt — APPROVED** [review]
LGTM 
(though, I personally don't like hover on checked or selected items, but U get the need)

**Pull request merged**
