### PR TITLE
fix(components): fix wrong appearance definition (VIV-1210)

### PR DESCRIPTION
**Pull request by rachelbt**

### CODE REVIEW

**Comment by YonatanKra** [comment]
Thanks for handling this.
Please add a UI test that covers this.

**Comment by rachelbt** [comment]
> Thanks for handling this. Please add a UI test that covers this.

there are both unit-test and UI test. 
image
Its like - it doesn't matter which layout is in the TS. The one that is in the css file is the one that counts...
Like - in text-field there was Layout.Outline - but it was not outlined but fieldset!

**Comment by YonatanKra** [comment]
> there are both unit-test and UI test. image Its like - it doesn't matter which layout is in the TS. The one that is in the css file is the one that counts... Like - in text-field there was Layout.Outline - but it was not outlined but fieldset!

So one would expect the examples to change now that you fixed it, no?

**Review by YonatanKra — APPROVED** [review]
I see it's typing issues.
Thanks for correcting it :)

**Pull request merged**
