### PR TITLE
fix(tabs): align with figma design

### PR DESCRIPTION
**Pull request by rinaok**
Screenshot 2023-01-17 at 16 19 14

Screenshot 2023-01-17 at 16 19 37

Me and @AyalaBu fixed tabs to align with figma.
@yinonov @rachelbt I have a problem with the width of of the indicator when animation.

### CODE REVIEW

**Comment by yinonov** [comment]
awaits design research @AyalaBu

**Comment by AyalaBu** [comment]
@rinaok @yinonov 
After a discussion and a research I propose to go back to the previous layout of the component, 
just like seen in this link:

https://ant.design/components/tabs

**Review by rinaok — COMMENTED** [review]
revert

**Comment by rinaok** [comment]
> @rinaok @yinonov After a discussion and a research I propose to go back to the previous layout of the component, just like seen in this link:
> 
> [ant.design/components/tabs](https://ant.design/components/tabs)

Screenshot 2023-01-23 at 20 14 22


@AyalaBu So when vertical, the indicator should look like this?

**Pull request closed without merging**
