### PR TITLE
refactor(docs): feature code block predefined layouts

### PR DESCRIPTION
**Pull request by yinonov**
introducing 4 types of layout for code blocks -

- inline (default)
- blocks
- columns
- full
- center

### CODE REVIEW

**Review by rachelbt — DISMISSED** [review]
LGTM

**Comment by yinonov** [comment]
> LGTM
Thanks. having 2nd thoughts on where to apply the required layout; maybe each code fence requires a different layout and not all code fences in a doc

**Review by rachelbt — COMMENTED** [review]
I love the idea of various types of layout!

I'm not so sure about the use of layout in buttons:
image

 also - in elevation - the items can use some margin on body :)
 
 Not sure about the colors of the `<code>` the red looks too much alerting  and the grey looks a bit too light.

**Review by YonatanKra — APPROVED** [review]
LGTM

**Pull request merged**
