### PR TITLE
refactor(components): change ts type and css property

### PR DESCRIPTION
**Pull request by yinonov**

### CODE REVIEW

**Comment by yinonov** [comment]
@rachelbt think we can contain body scroll as well in modal mode?
(can reproduce setting the docs website's drawer to modal)

**Comment by rachelbt** [comment]
> @rachelbt think we can contain body scroll as well in modal mode? (can reproduce setting the docs website's drawer to modal)
```

background-color: var(--vvd-color-on-canvas);
position: fixed;
inset: 0px;
color: wheat;
pointer-events: all;
overscroll-behavior: contain;
opacity: 0.5;
overflow: overlay;
```
don’t forget to remove the inert:
`<div class="side-drawer-app-content" inert="">`

**Comment by yinonov** [comment]
this solution only works if overlay is scrollable. If all content fit on screen within an element setting `overscroll-behavior: contain`, but there is no scroll inside — it will not stop the body scroll

**Comment by yinonov** [comment]
handled better in #527

**Pull request closed without merging**
