### PR TITLE
feat(docs): add density button to code block demo

### PR DESCRIPTION
**Pull request by olaf-k**
[as discussed here](https://github.com/Vonage/vivid-3/issues/770#issuecomment-1303916622)

### CODE REVIEW

**Comment by yinonov** [comment]
nice!🚀  we still need to ensure #780 resolves properly. and probably have this reviewed from a design perspective @AyalaBu

**Review by rachelbt — COMMENTED** [review]
@yinonov de we want to expose it?
I find it a bit confusing with no explanation what is the density for. 
User may use it instead of the sizes that we offer.
Also, if this is to be merged ,we need to first merge the change of "density" property to Size before we add this.

**Comment by olaf-k** [comment]
> I find it a bit confusing with no explanation what is the density for.

[The doc PR](https://github.com/Vonage/vivid-3/pull/791/files#diff-2a2b78a5afbea89fab9c9618e96a4f23baa23713dd777583346a589c5ffab3c1R45) would be a prerequisite indeed.

**Comment by rachelbt** [comment]
> is for it to be a low profile interface and not be exposed at all?

I think `--vvd-size-density` is for high-level users and it should be a low profile interface and not be exposed as a button to play with. 
We should document it as in the other PR, but not present it and cause our user to use it wrongly (no one will read the doc unless they will need it....) they will just set the density instead-of using "size", and this will be wrong usage

**Pull request closed without merging**
