### PR TITLE
fix(docs): colors suggestion

### PR DESCRIPTION
**Pull request by rachelbt**

### CODE REVIEW

**Comment by AyalaBu** [comment]
@rachelbt 
It looks nice,
but from the accessibility point of view based on Joella's algorithm,
it is better in the dark theme to use CTA 400 instead of 500.

**Comment by rachelbt** [comment]
> @rachelbt It looks nice, but from the accessibility point of view based on Joella's algorithm, it is better in the dark theme to use CTA 400 instead of 500.
> 
> Also, the code line of installation is not accessible.
> 
> As are all the code remarks.

@AyalaBu as we spoked - I changed the code snippets colors:
https://vivid-n7pj66a6hr70.deno.dev/

**Comment by yinonov** [comment]
it feels too colorful now. it's subjective but I'd follow something like https://docsify.js.org/#/?id=docsify

**Comment by AyalaBu** [comment]
@rachelbt @yinonov 
I guess the variety of colors can be reduced,
but the tokens numbers must stay the same in order to keep the page accessible

**Comment by yinonov** [comment]
Were there contrast issues?

**Comment by AyalaBu** [comment]
Absolutely!
It was unaccessible in most cases when the code text is involved

**Comment by yinonov** [comment]
> @yinonov Absolutely! It was unaccessible in most cases when the code text is involved

@AyalaBu can u show me where? automated check have didn't throw any exceptions

**Comment by rachelbt** [comment]
> > @yinonov Absolutely! It was unaccessible in most cases when the code text is involved
> 
> @AyalaBu can u show me where? (a screenshot will do) automated check have didn't throw any exceptions

image

**Comment by yinonov** [comment]
> > > @yinonov Absolutely! It was unaccessible in most cases when the code text is involved
> > 
> > 
> > @AyalaBu can u show me where? (a screenshot will do) automated check have didn't throw any exceptions
> 
> image

should be resolved by #790

**Comment by yinonov** [comment]
besides code coloring issues, is this PR still relevant?

**Comment by olaf-k** [comment]
> should be resolved by #790

(tl;dr: it proposes `--vvd-color-neutral-600` for code blocks and should work in both modes.)

**Comment by rachelbt** [comment]
> besides code coloring issues, is this PR still relevant?

don't know.... I changed the cta color to pattern:
image

**Review by yinonov — APPROVED** [review]
LGTM

**Pull request merged**
