### PR TITLE
chore(workspace): run e2e in Windows

### PR DESCRIPTION
**Pull request by olaf-k**
This PR just makes it easier for Windows users to launch e2e tests. It:
- provides a .cmd batch script to run the docker image.
- preserves LF line endings in .sh script files.

### CODE REVIEW

**Review by yinonov — APPROVED** [review]

**Comment by YonatanKra** [comment]
@yinonov Does this work for you on a windows machine?

**Review by yinonov — APPROVED** [review]

**Comment by yinonov** [comment]
> 

I don't use windows

**Comment by yinonov** [comment]
> @yinonov Does this work for you on a windows machine?

@YonatanKra I don't use windows. if this doesn't affect mac in anyway, is there a reason to preclude this?

**Comment by yinonov** [comment]
still relevant?

**Review by YonatanKra — APPROVED** [review]
LGTM

**Pull request merged**
